USE sql9147193;

CREATE TABLE Obra (
 ID INT   NOT NULL,
 NOME VARCHAR(100)  NOT NULL,
 SERIAL VARCHAR(50) NOT NULL,
 VALOR DECIMAL(18,2) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE Responsavel (
ID INT NOT NULL,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(25) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE Usuario (
ID  INT NOT NULL,
EMAIL VARCHAR(25) NOT NULL,
SENHA VARCHAR(25) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO Usuario (ID, EMAIL, SENHA)
VALUES (1,teste@teste, teste);
